
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myjrgdcdbkunhcsutxvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15anJnZGNkYmt1bmhjc3V0eHZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODM4NjEsImV4cCI6MjA2MTY1OTg2MX0.uDHXgBN99tDKgo2MJwLAV41fmHIsO2I9GggGziCTd5I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
